### ISSUE TITLE
Traduzir os formularios de Accounts

### ISSUE THREAD

**Issue by lnmunhoz** [bornscale/safed-admin#15]
Traduzir os forms de enroll, reset password, etc... Seguindo o que fiz nesse commit cbcce89150f4ca8fe15b7d1ee305129bd1ea6733

useraccount docs:
https://github.com/meteor-useraccounts/core/blob/master/Guide.md#options

**Comment by ifalldev** [comment]
Traduções feitas, só preciso fazer mais alguns testes para saber se deixei passar algo.

E o titulo do enroll ta quebrando, terminando a verificação da tradução eu vou dar um jeito nisso.
