### ISSUE TITLE
Visualização por listView

### ISSUE THREAD

**Issue by lnmunhoz** [bornscale/safed-admin#17]
Vai possuir? se não vamos remover o `searchDisplayMode`.

**Comment by rafaelcorreiapoli** [comment]
To pensando em meter um Tabular lá e já era. O cliente é meio das antigas, acho que ele gosta de tabelinha

**Comment by lnmunhoz** [comment]
Deixei sem o searchDisplayMode e o Grid está default por enquando. 4a20068a5160f1f9c369c94f2f44e5bbb8b490e3
