### ISSUE TITLE
Alinhamento dos formulários

### ISSUE THREAD

**Issue by lnmunhoz** [bornscale/safed-admin#20]
Arrumar para todos os inputs formulários e alinhamento dos botões:

**inputs**
- `label-class="col-sm-2"`
- `input-col-class="col-sm-10"`

**submit buttons**
- `buttonClass="col-sm-10"`
- `offsetClass="col-sm-offset-2"`

Seguir exemplo de [user_invite.html](https://github.com/bornscale/safed-admin/blob/master/client/views/users/users_invite/users_invite.html).

**Comment by rafaelcorreiapoli** [comment]
É interessante usar a função de replace global do sublime

**Comment by lnmunhoz** [comment]
Fixed here 726be3e
