### ISSUE TITLE
Bug na busca por CNH

### ISSUE THREAD

**Issue by lnmunhoz** [bornscale/safed-admin#21]
![screenshot 2016-03-20 22 24 41](https://cloud.githubusercontent.com/assets/4376835/13908849/b8e8f48a-eeea-11e5-91ca-f9731b865101.png)

**Comment by rafaelcorreiapoli** [comment]
```
{{{ cnh }}}
```

**Comment by lnmunhoz** [comment]
Fixed here d6f1ed4
